package util.xml;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * 
 * In MiMus, an object is Writable if it can be written down to
 * an XML document that conforms the annotated corpus. Classes
 * implementing MiMusWritable are, in general, model objects that
 * have specific parameters which must be expressed as an XML
 * element in the corpus. The method toXMLElement() returns this
 * XML element. The name of the root entry is returned by the
 * method getWritableName().
 * 
 * In order to write an object into an XML, another information
 * needed is where to store it, i.e. under which XML entry. The
 * method getWritableCategory() returns the name of the XML entry
 * that will be parent of the element created by toXMLElement().
 * 
 * All methods are accessed by MiMusXMLWriter, which contains the
 * functionality to write the corpus to XML files, and it's called
 * from the UI actions.
 * 
 * @author Javier Beltrán Jorba
 *
 */
public interface MiMusWritable {
	
	/**
	 * Converts a model object into an XML Element that can be
	 * appended to an XML Document.
	 */
	public Element toXMLElement(Document doc);
	
	/**
	 * Returns the name of the root entry in the XML element
	 * generated by toXMLElement();
	 */
	public String getWritableName();
	
	/**
	 * Returns the name of the XML entry that must be used as
	 * parent of the XML Element generated by toXMLElement().
	 */
	public String getWritableCategory();
	
}
